### ISSUE TITLE
Certificate error does not end process

### ISSUE THREAD

**Issue by cthayer** [Daplie/letsencrypt-cli#14]
If there is an error creating or renewing a certificate, the process does not end without manual intervention.

This causes an issue in scripted environments where certificates are renewed automatically using the `standalone` method as ports 80 and 443 remain bound and cause other automated certificate renewal requests to fail because they can't bind to port 80 and 443.

In all cases, I would expect a failure to renew a certificate to result in the process exiting with a non-zero exit code.

I'm running nodejs v5.7.0 and an example command is below:

```bash
/usr/local/bin/letsencrypt certonly --agree-tos --email email@example.com --config-dir /etc/letsencrypt --standalone --duplicate --domains a.example.com,b.example.com,c.example.com
```

**Comment by coolaj86** [comment]
This is fixed in v2.0.0, which was just published.
https://github.com/Daplie/letsencrypt-cli

**Comment by cthayer** [comment]
Thanks!

Now just need issue #19 addressed and I'll be able to upgrade :)

**Comment by coolaj86** [comment]
v2.1.1 fixes bug introduced in v2.1.0

I need some help testing.

I don't always run the tests when I think I'm making a "small change" (and then ended up with a typo with an extra 's' on server) because even the test server rate-limits.

So either I need some help being able to say "hey, here's a new version, can you test it with your normal development setup" or to get a mock test server of our own that doesn't rate limit.

Any suggestions?

**Comment by coolaj86** [comment]
(I did run a partial test on this, but I let it fail the validation since the part that I changed happens before `le.challenge.remove` and if it passes validation that counts against my daily rate limit and I'm also working on `letsencrypt-express` and need to be able to run the tests on that today too)

**Comment by cthayer** [comment]
Definitely a problem.

I assume that your testing with their staging environment?

https://letsencrypt.org/docs/staging-environment/

I ask because they say using the staging environment will "reduce the chance of your running up against rate limits"

Though I haven't been able to find anything that talks about the rate limits not being applied to the staging environment...

**Comment by cthayer** [comment]
Some more investigation on the testing subject lead me to this comment:

https://community.letsencrypt.org/t/rate-limit-on-staging-server/11205/3

They suggest running a local instance of [Boulder](https://github.com/letsencrypt/boulder) if you're doing a large volume of testing (though I think it really applies to non-trivial volumes of testing).

I think that using a local instance of Boulder is the best way to achieve reliable tests.
